---
abstract: 'suggest terms for Apache Lucy search'
author:
  - 'Peter Karman, C<< <karman at cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: http://dev.perl.org/licenses/
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LucyX-Suggester
no_index:
  directory:
    - inc
    - t
requires:
  Data::Dump: 0
  Lucy: 0.003002
  Search::Tools: 0.83
  Test::More: 0
  Text::Aspell: 0
  perl: 5.8.3
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=LucyX-Suggester
  homepage: https://github.com/karpet/lucyx-suggester
  license: http://opensource.org/licenses/gpl-license.php
  repository: https://github.com/karpet/lucyx-suggester
version: 0.001
